const carsData = [
    {
        id: 1,
        brand: "Toyota",
        model: "Camry",
        year: 2024,
        price: 3500,
        hp: 200,
        type: "Седан",
        engine: "2.5L бензин",
        transmission: "Автомат",
        color: "Белый",
        description: "Надежный и комфортный седан бизнес-класса. Идеально подходит для ежедневных поездок и деловых встреч.",
        images: ["images/toyota_camry_1.jpg", "images/toyota_camry_2.jpg", "images/toyota_camry_3.jpg"]
    },
    {
        id: 2,
        brand: "BMW",
        model: "3 Series",
        year: 2024,
        price: 5500,
        hp: 249,
        type: "Седан",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Спортивный седан премиум-класса с отличной динамикой и управляемостью.",
        images: ["images/bmw_3_1.jpg", "images/bmw_3_2.jpg", "images/bmw_3_3.jpg"]
    },
    {
        id: 3,
        brand: "Mercedes",
        model: "C-Class",
        year: 2024,
        price: 6000,
        hp: 258,
        type: "Седан",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Серебристый",
        description: "Элегантный седан с роскошным салоном и передовыми технологиями безопасности.",
        images: ["images/mercedes_c_1.jpg", "images/mercedes_c_2.jpg", "images/mercedes_c_3.jpg"]
    },
    {
        id: 4,
        brand: "Audi",
        model: "A4",
        year: 2024,
        price: 5200,
        hp: 245,
        type: "Седан",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Синий",
        description: "Технологичный седан с полным приводом Quattro и премиальным интерьером.",
        images: ["images/audi_a4_1.jpg", "images/audi_a4_2.jpg", "images/audi_a4_3.jpg"]
    },
    {
        id: 5,
        brand: "Volkswagen",
        model: "Tiguan",
        year: 2024,
        price: 4200,
        hp: 180,
        type: "Кроссовер",
        engine: "1.4L турбо",
        transmission: "Автомат",
        color: "Красный",
        description: "Семейный кроссовер с просторным салоном и большим багажником.",
        images: ["images/vw_tiguan_1.jpg", "images/vw_tiguan_2.jpg", "images/vw_tiguan_3.jpg"]
    },
    {
        id: 6,
        brand: "Hyundai",
        model: "Tucson",
        year: 2024,
        price: 3800,
        hp: 150,
        type: "Кроссовер",
        engine: "2.0L бензин",
        transmission: "Автомат",
        color: "Зеленый",
        description: "Современный кроссовер с футуристичным дизайном и богатым оснащением.",
        images: ["images/hyundai_tucson_1.jpg", "images/hyundai_tucson_2.jpg", "images/hyundai_tucson_3.jpg"]
    },
    {
        id: 7,
        brand: "Kia",
        model: "K5",
        year: 2024,
        price: 3400,
        hp: 180,
        type: "Седан",
        engine: "2.5L бензин",
        transmission: "Автомат",
        color: "Серый",
        description: "Стильный седан с динамичным дизайном и комфортным салоном.",
        images: ["images/kia_k5_1.jpg", "images/kia_k5_2.jpg", "images/kia_k5_3.jpg"]
    },
    {
        id: 8,
        brand: "Tesla",
        model: "Model 3",
        year: 2024,
        price: 7000,
        hp: 283,
        type: "Седан",
        engine: "Электро",
        transmission: "Автомат",
        color: "Белый",
        description: "Электрический седан с автопилотом и впечатляющей динамикой разгона.",
        images: ["images/tesla_model3_1.jpg", "images/tesla_model3_2.jpg", "images/tesla_model3_3.jpg"]
    },
    {
        id: 9,
        brand: "Lexus",
        model: "RX",
        year: 2024,
        price: 7500,
        hp: 275,
        type: "Кроссовер",
        engine: "2.4L турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Премиальный кроссовер с высочайшим уровнем комфорта и надежности.",
        images: ["images/lexus_rx_1.jpg", "images/lexus_rx_2.jpg", "images/lexus_rx_3.jpg"]
    },
    {
        id: 10,
        brand: "Porsche",
        model: "Cayenne",
        year: 2024,
        price: 12000,
        hp: 340,
        type: "Кроссовер",
        engine: "3.0L турбо",
        transmission: "Автомат",
        color: "Белый",
        description: "Спортивный кроссовер с превосходной управляемостью и роскошным интерьером.",
        images: ["images/porsche_cayenne_1.jpg", "images/porsche_cayenne_2.jpg", "images/porsche_cayenne_3.jpg"]
    },
    {
        id: 11,
        brand: "Toyota",
        model: "RAV4",
        year: 2024,
        price: 4000,
        hp: 199,
        type: "Кроссовер",
        engine: "2.5L бензин",
        transmission: "Автомат",
        color: "Синий",
        description: "Популярный кроссовер с надежной конструкцией и экономичным расходом.",
        images: ["images/toyota_rav4_1.jpg", "images/toyota_rav4_2.jpg", "images/toyota_rav4_3.jpg"]
    },
    {
        id: 12,
        brand: "BMW",
        model: "X5",
        year: 2024,
        price: 9500,
        hp: 340,
        type: "Кроссовер",
        engine: "3.0L турбо",
        transmission: "Автомат",
        color: "Серый",
        description: "Премиальный кроссовер с мощным двигателем и роскошным оснащением.",
        images: ["images/bmw_x5_1.jpg", "images/bmw_x5_2.jpg", "images/bmw_x5_3.jpg"]
    },
    {
        id: 13,
        brand: "Mercedes",
        model: "GLC",
        year: 2024,
        price: 8000,
        hp: 258,
        type: "Кроссовер",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Красный",
        description: "Компактный премиальный кроссовер с элегантным дизайном.",
        images: ["images/mercedes_glc_1.jpg", "images/mercedes_glc_2.jpg", "images/mercedes_glc_3.jpg"]
    },
    {
        id: 14,
        brand: "Audi",
        model: "Q5",
        year: 2024,
        price: 7200,
        hp: 249,
        type: "Кроссовер",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Белый",
        description: "Стильный кроссовер с полным приводом и технологичным интерьером.",
        images: ["images/audi_q5_1.jpg", "images/audi_q5_2.jpg", "images/audi_q5_3.jpg"]
    },
    {
        id: 15,
        brand: "Hyundai",
        model: "Solaris",
        year: 2024,
        price: 2500,
        hp: 123,
        type: "Седан",
        engine: "1.6L бензин",
        transmission: "Автомат",
        color: "Серебристый",
        description: "Экономичный седан для ежедневных городских поездок.",
        images: ["images/hyundai_solaris_1.jpg", "images/hyundai_solaris_2.jpg", "images/hyundai_solaris_3.jpg"]
    },
    {
        id: 16,
        brand: "Kia",
        model: "Sportage",
        year: 2024,
        price: 4100,
        hp: 180,
        type: "Кроссовер",
        engine: "2.0L бензин",
        transmission: "Автомат",
        color: "Черный",
        description: "Современный кроссовер с ярким дизайном и богатым оснащением.",
        images: ["images/kia_sportage_1.jpg", "images/kia_sportage_2.jpg", "images/kia_sportage_3.jpg"]
    },
    {
        id: 17,
        brand: "Volkswagen",
        model: "Golf",
        year: 2024,
        price: 3200,
        hp: 150,
        type: "Хэтчбек",
        engine: "1.4L турбо",
        transmission: "Автомат",
        color: "Синий",
        description: "Легендарный хэтчбек с отличной управляемостью и качеством сборки.",
        images: ["images/vw_golf_1.jpg", "images/vw_golf_2.jpg", "images/vw_golf_3.jpg"]
    },
    {
        id: 18,
        brand: "Tesla",
        model: "Model Y",
        year: 2024,
        price: 8500,
        hp: 384,
        type: "Кроссовер",
        engine: "Электро",
        transmission: "Автомат",
        color: "Красный",
        description: "Электрический кроссовер с большим запасом хода и автопилотом.",
        images: ["images/tesla_modely_1.jpg", "images/tesla_modely_2.jpg", "images/tesla_modely_3.jpg"]
    },
    {
        id: 19,
        brand: "Lexus",
        model: "ES",
        year: 2024,
        price: 6800,
        hp: 249,
        type: "Седан",
        engine: "2.5L гибрид",
        transmission: "Автомат",
        color: "Черный",
        description: "Роскошный гибридный седан с непревзойденным комфортом.",
        images: ["images/lexus_es_1.jpg", "images/lexus_es_2.jpg", "images/lexus_es_3.jpg"]
    },
    {
        id: 20,
        brand: "Porsche",
        model: "911",
        year: 2024,
        price: 18000,
        hp: 385,
        type: "Купе",
        engine: "3.0L турбо",
        transmission: "Автомат",
        color: "Желтый",
        description: "Легендарный спортивный автомобиль с выдающейся динамикой.",
        images: ["images/porsche_911_1.jpg", "images/porsche_911_2.jpg", "images/porsche_911_3.jpg"]
    },
    {
        id: 21,
        brand: "Ferrari",
        model: "F8 Tributo",
        year: 2024,
        price: 45000,
        hp: 720,
        type: "Купе",
        engine: "3.9L V8 турбо",
        transmission: "Автомат",
        color: "Красный",
        description: "Легендарный суперкар с невероятной мощностью и итальянским дизайном.",
        images: ["images/ferrari_f8_1.jpg", "images/ferrari_f8_2.jpg", "images/ferrari_f8_3.jpg"]
    },
    {
        id: 22,
        brand: "Ferrari",
        model: "Roma",
        year: 2024,
        price: 38000,
        hp: 620,
        type: "Купе",
        engine: "3.9L V8 турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Элегантный гран-туризмо с роскошным интерьером и спортивным характером.",
        images: ["images/ferrari_roma_1.jpg", "images/ferrari_roma_2.jpg", "images/ferrari_roma_3.jpg"]
    },
    {
        id: 23,
        brand: "Ferrari",
        model: "SF90 Stradale",
        year: 2024,
        price: 55000,
        hp: 1000,
        type: "Купе",
        engine: "4.0L V8 гибрид",
        transmission: "Автомат",
        color: "Желтый",
        description: "Гибридный суперкар с рекордной мощностью и передовыми технологиями.",
        images: ["images/ferrari_sf90_1.jpg", "images/ferrari_sf90_2.jpg", "images/ferrari_sf90_3.jpg"]
    },
    {
        id: 24,
        brand: "Ferrari",
        model: "296 GTB",
        year: 2024,
        price: 42000,
        hp: 830,
        type: "Купе",
        engine: "3.0L V6 гибрид",
        transmission: "Автомат",
        color: "Белый",
        description: "Среднемоторный спорткар с гибридной силовой установкой.",
        images: ["images/ferrari_296_1.jpg", "images/ferrari_296_2.jpg", "images/ferrari_296_3.jpg"]
    },
    {
        id: 25,
        brand: "Dodge",
        model: "Challenger SRT",
        year: 2024,
        price: 8500,
        hp: 717,
        type: "Купе",
        engine: "6.2L V8",
        transmission: "Автомат",
        color: "Оранжевый",
        description: "Мощный маслкар с агрессивным дизайном и ревущим двигателем.",
        images: ["images/dodge_challenger_1.jpg", "images/dodge_challenger_2.jpg", "images/dodge_challenger_3.jpg"]
    },
    {
        id: 26,
        brand: "Dodge",
        model: "Charger SRT",
        year: 2024,
        price: 7800,
        hp: 707,
        type: "Седан",
        engine: "6.2L V8",
        transmission: "Автомат",
        color: "Черный",
        description: "Самый мощный серийный седан в мире с американским характером.",
        images: ["images/dodge_charger_1.jpg", "images/dodge_charger_2.jpg", "images/dodge_charger_3.jpg"]
    },
    {
        id: 27,
        brand: "Dodge",
        model: "Durango SRT",
        year: 2024,
        price: 9000,
        hp: 475,
        type: "Кроссовер",
        engine: "6.4L V8",
        transmission: "Автомат",
        color: "Красный",
        description: "Спортивный внедорожник с мощным V8 и просторным салоном.",
        images: ["images/dodge_durango_1.jpg", "images/dodge_durango_2.jpg", "images/dodge_durango_3.jpg"]
    },
    {
        id: 28,
        brand: "Dodge",
        model: "Hornet",
        year: 2024,
        price: 5500,
        hp: 268,
        type: "Кроссовер",
        engine: "2.0L турбо",
        transmission: "Автомат",
        color: "Синий",
        description: "Компактный кроссовер с динамичным характером и современным дизайном.",
        images: ["images/dodge_hornet_1.jpg", "images/dodge_hornet_2.jpg", "images/dodge_hornet_3.jpg"]
    },
    {
        id: 29,
        brand: "Bentley",
        model: "Continental GT",
        year: 2024,
        price: 35000,
        hp: 659,
        type: "Купе",
        engine: "6.0L W12",
        transmission: "Автомат",
        color: "Зеленый",
        description: "Роскошное гран-туризмо с безупречным британским качеством.",
        images: ["images/bentley_continental_1.jpg", "images/bentley_continental_2.jpg", "images/bentley_continental_3.jpg"]
    },
    {
        id: 30,
        brand: "Bentley",
        model: "Flying Spur",
        year: 2024,
        price: 32000,
        hp: 626,
        type: "Седан",
        engine: "6.0L W12",
        transmission: "Автомат",
        color: "Черный",
        description: "Премиальный седан с непревзойденной роскошью и комфортом.",
        images: ["images/bentley_flying_1.jpg", "images/bentley_flying_2.jpg", "images/bentley_flying_3.jpg"]
    },
    {
        id: 31,
        brand: "Bentley",
        model: "Bentayga",
        year: 2024,
        price: 30000,
        hp: 542,
        type: "Кроссовер",
        engine: "4.0L V8",
        transmission: "Автомат",
        color: "Синий",
        description: "Самый роскошный внедорожник в мире с британской элегантностью.",
        images: ["images/bentley_bentayga_1.jpg", "images/bentley_bentayga_2.jpg", "images/bentley_bentayga_3.jpg"]
    },
    {
        id: 32,
        brand: "Bentley",
        model: "Bentayga EWB",
        year: 2024,
        price: 38000,
        hp: 626,
        type: "Кроссовер",
        engine: "6.0L W12",
        transmission: "Автомат",
        color: "Белый",
        description: "Удлиненная версия Bentayga с максимальным комфортом для задних пассажиров.",
        images: ["images/bentley_bentayga_ewb_1.jpg", "images/bentley_bentayga_ewb_2.jpg", "images/bentley_bentayga_ewb_3.jpg"]
    },
    {
        id: 33,
        brand: "Bugatti",
        model: "Chiron",
        year: 2024,
        price: 120000,
        hp: 1500,
        type: "Купе",
        engine: "8.0L W16",
        transmission: "Автомат",
        color: "Синий",
        description: "Гиперкар с невероятной мощностью W16 и скоростью более 400 км/ч.",
        images: ["images/bugatti_chiron_1.jpg", "images/bugatti_chiron_2.jpg", "images/bugatti_chiron_3.jpg"]
    },
    {
        id: 34,
        brand: "Bugatti",
        model: "Mistral",
        year: 2024,
        price: 150000,
        hp: 1600,
        type: "Купе",
        engine: "8.0L W16",
        transmission: "Автомат",
        color: "Белый",
        description: "Родстер-гиперкар с открытым верхом и рекордной мощностью.",
        images: ["images/bugatti_mistral_1.jpg", "images/bugatti_mistral_2.jpg", "images/bugatti_mistral_3.jpg"]
    },
    {
        id: 35,
        brand: "McLaren",
        model: "720S",
        year: 2024,
        price: 38000,
        hp: 720,
        type: "Купе",
        engine: "4.0L V8 турбо",
        transmission: "Автомат",
        color: "Оранжевый",
        description: "Суперкар с карбоновым монококом и феноменальной аэродинамикой.",
        images: ["images/mclaren_720s_1.jpg", "images/mclaren_720s_2.jpg", "images/mclaren_720s_3.jpg"]
    },
    {
        id: 36,
        brand: "McLaren",
        model: "Artura",
        year: 2024,
        price: 32000,
        hp: 680,
        type: "Купе",
        engine: "3.0L V6 гибрид",
        transmission: "Автомат",
        color: "Серый",
        description: "Гибридный суперкар нового поколения с легким карбоновым шасси.",
        images: ["images/mclaren_artura_1.jpg", "images/mclaren_artura_2.jpg", "images/mclaren_artura_3.jpg"]
    },
    {
        id: 37,
        brand: "McLaren",
        model: "GT",
        year: 2024,
        price: 28000,
        hp: 620,
        type: "Купе",
        engine: "4.0L V8 турбо",
        transmission: "Автомат",
        color: "Серебристый",
        description: "Гран-туризмо от McLaren с комфортом для длительных поездок.",
        images: ["images/mclaren_gt_1.jpg", "images/mclaren_gt_2.jpg", "images/mclaren_gt_3.jpg"]
    },
    {
        id: 38,
        brand: "McLaren",
        model: "750S",
        year: 2024,
        price: 45000,
        hp: 750,
        type: "Купе",
        engine: "4.0L V8 турбо",
        transmission: "Автомат",
        color: "Зеленый",
        description: "Эволюция легендарного 720S с увеличенной мощностью и аэродинамикой.",
        images: ["images/mclaren_750s_1.jpg", "images/mclaren_750s_2.jpg", "images/mclaren_750s_3.jpg"]
    },
    {
        id: 39,
        brand: "Bugatti",
        model: "Bolide",
        year: 2024,
        price: 180000,
        hp: 1824,
        type: "Купе",
        engine: "8.0L W16",
        transmission: "Автомат",
        color: "Черный",
        description: "Трековый гиперкар с рекордным соотношением мощности к массе.",
        images: ["images/bugatti_bolide_1.jpg", "images/bugatti_bolide_2.jpg", "images/bugatti_bolide_3.jpg"]
    },
    {
        id: 40,
        brand: "McLaren",
        model: "Senna",
        year: 2024,
        price: 65000,
        hp: 800,
        type: "Купе",
        engine: "4.0L V8 турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Легендарный трековый суперкар, названный в честь Айртона Сенны.",
        images: ["images/mclaren_senna_1.jpg", "images/mclaren_senna_2.jpg", "images/mclaren_senna_3.jpg"]
    },
    {
        id: 41,
        brand: "Nissan",
        model: "GT-R",
        year: 2024,
        price: 15000,
        hp: 565,
        type: "Купе",
        engine: "3.8L V6 турбо",
        transmission: "Автомат",
        color: "Красный",
        description: "Легендарный японский суперкар с полным приводом и невероятным разгоном.",
        images: ["images/nissan_gtr_1.jpg", "images/nissan_gtr_2.jpg", "images/nissan_gtr_3.jpg"]
    },
    {
        id: 42,
        brand: "Nissan",
        model: "Leaf",
        year: 2024,
        price: 3000,
        hp: 150,
        type: "Хэтчбек",
        engine: "Электро",
        transmission: "Автомат",
        color: "Белый",
        description: "Популярный электромобиль для ежедневных городских поездок.",
        images: ["images/nissan_leaf_1.jpg", "images/nissan_leaf_2.jpg", "images/nissan_leaf_3.jpg"]
    },
    {
        id: 43,
        brand: "Nissan",
        model: "X-Trail",
        year: 2024,
        price: 4200,
        hp: 170,
        type: "Кроссовер",
        engine: "2.5L бензин",
        transmission: "Автомат",
        color: "Серый",
        description: "Семейный кроссовер с просторным салоном и надежной конструкцией.",
        images: ["images/nissan_xtrail_1.jpg", "images/nissan_xtrail_2.jpg", "images/nissan_xtrail_3.jpg"]
    },
    {
        id: 44,
        brand: "Nissan",
        model: "370Z",
        year: 2024,
        price: 6500,
        hp: 350,
        type: "Купе",
        engine: "3.7L V6",
        transmission: "Механика",
        color: "Синий",
        description: "Классический спортивный автомобиль с задним приводом и мощным двигателем.",
        images: ["images/nissan_370z_1.jpg", "images/nissan_370z_2.jpg", "images/nissan_370z_3.jpg"]
    },
    {
        id: 45,
        brand: "Mazda",
        model: "CX-5",
        year: 2024,
        price: 3800,
        hp: 194,
        type: "Кроссовер",
        engine: "2.5L бензин",
        transmission: "Автомат",
        color: "Красный",
        description: "Стильный кроссовер с премиальным интерьером и отличной управляемостью.",
        images: ["images/mazda_cx5_1.jpg", "images/mazda_cx5_2.jpg", "images/mazda_cx5_3.jpg"]
    },
    {
        id: 46,
        brand: "Mazda",
        model: "3",
        year: 2024,
        price: 2800,
        hp: 150,
        type: "Хэтчбек",
        engine: "2.0L бензин",
        transmission: "Автомат",
        color: "Белый",
        description: "Элегантный хэтчбек с фирменным дизайном Kodo и экономичным двигателем.",
        images: ["images/mazda_3_1.jpg", "images/mazda_3_2.jpg", "images/mazda_3_3.jpg"]
    },
    {
        id: 47,
        brand: "Mazda",
        model: "MX-5",
        year: 2024,
        price: 5500,
        hp: 184,
        type: "Купе",
        engine: "2.0L бензин",
        transmission: "Механика",
        color: "Красный",
        description: "Легендарный родстер с идеальным распределением веса и удовольствием от вождения.",
        images: ["images/mazda_mx5_1.jpg", "images/mazda_mx5_2.jpg", "images/mazda_mx5_3.jpg"]
    },
    {
        id: 48,
        brand: "Mazda",
        model: "CX-9",
        year: 2024,
        price: 5000,
        hp: 231,
        type: "Кроссовер",
        engine: "2.5L турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Большой семейный кроссовер с тремя рядами сидений.",
        images: ["images/mazda_cx9_1.jpg", "images/mazda_cx9_2.jpg", "images/mazda_cx9_3.jpg"]
    },
    {
        id: 49,
        brand: "Chevrolet",
        model: "Corvette C8",
        year: 2024,
        price: 18000,
        hp: 495,
        type: "Купе",
        engine: "6.2L V8",
        transmission: "Автомат",
        color: "Желтый",
        description: "Американский суперкар со среднемоторной компоновкой и впечатляющей динамикой.",
        images: ["images/chevrolet_corvette_1.jpg", "images/chevrolet_corvette_2.jpg", "images/chevrolet_corvette_3.jpg"]
    },
    {
        id: 50,
        brand: "Chevrolet",
        model: "Tahoe",
        year: 2024,
        price: 8500,
        hp: 355,
        type: "Кроссовер",
        engine: "5.3L V8",
        transmission: "Автомат",
        color: "Черный",
        description: "Полноразмерный внедорожник с мощным V8 и просторным салоном.",
        images: ["images/chevrolet_tahoe_1.jpg", "images/chevrolet_tahoe_2.jpg", "images/chevrolet_tahoe_3.jpg"]
    },
    {
        id: 51,
        brand: "Chevrolet",
        model: "Camaro",
        year: 2024,
        price: 7500,
        hp: 455,
        type: "Купе",
        engine: "6.2L V8",
        transmission: "Автомат",
        color: "Оранжевый",
        description: "Классический маслкар с агрессивным дизайном и мощным двигателем.",
        images: ["images/chevrolet_camaro_1.jpg", "images/chevrolet_camaro_2.jpg", "images/chevrolet_camaro_3.jpg"]
    },
    {
        id: 52,
        brand: "Chevrolet",
        model: "Equinox",
        year: 2024,
        price: 3500,
        hp: 175,
        type: "Кроссовер",
        engine: "1.5L турбо",
        transmission: "Автомат",
        color: "Серебристый",
        description: "Компактный кроссовер с экономичным двигателем и современным дизайном.",
        images: ["images/chevrolet_equinox_1.jpg", "images/chevrolet_equinox_2.jpg", "images/chevrolet_equinox_3.jpg"]
    },
    {
        id: 53,
        brand: "Ford",
        model: "Mustang GT",
        year: 2024,
        price: 8000,
        hp: 480,
        type: "Купе",
        engine: "5.0L V8",
        transmission: "Механика",
        color: "Синий",
        description: "Легендарный маслкар с ревущим V8 и культовым дизайном.",
        images: ["images/ford_mustang_1.jpg", "images/ford_mustang_2.jpg", "images/ford_mustang_3.jpg"]
    },
    {
        id: 54,
        brand: "Ford",
        model: "Explorer",
        year: 2024,
        price: 5500,
        hp: 300,
        type: "Кроссовер",
        engine: "2.3L турбо",
        transmission: "Автомат",
        color: "Черный",
        description: "Семейный внедорожник с тремя рядами сидений и мощным двигателем.",
        images: ["images/ford_explorer_1.jpg", "images/ford_explorer_2.jpg", "images/ford_explorer_3.jpg"]
    },
    {
        id: 55,
        brand: "Ford",
        model: "F-150",
        year: 2024,
        price: 7000,
        hp: 400,
        type: "Кроссовер",
        engine: "3.5L V6 турбо",
        transmission: "Автомат",
        color: "Серый",
        description: "Самый продаваемый пикап в Америке с невероятной грузоподъемностью.",
        images: ["images/ford_f150_1.jpg", "images/ford_f150_2.jpg", "images/ford_f150_3.jpg"]
    },
    {
        id: 56,
        brand: "Ford",
        model: "Bronco",
        year: 2024,
        price: 6500,
        hp: 330,
        type: "Кроссовер",
        engine: "2.7L V6 турбо",
        transmission: "Автомат",
        color: "Зеленый",
        description: "Внедорожник для настоящих приключений с возможностью съемной крыши.",
        images: ["images/ford_bronco_1.jpg", "images/ford_bronco_2.jpg", "images/ford_bronco_3.jpg"]
    },
    {
        id: 57,
        brand: "Lamborghini",
        model: "Huracan",
        year: 2024,
        price: 55000,
        hp: 640,
        type: "Купе",
        engine: "5.2L V10",
        transmission: "Автомат",
        color: "Зеленый",
        description: "Суперкар с атмосферным V10 и итальянским дизайном, от которого захватывает дух.",
        images: ["images/lambo_huracan_1.jpg", "images/lambo_huracan_2.jpg", "images/lambo_huracan_3.jpg"]
    },
    {
        id: 58,
        brand: "Lamborghini",
        model: "Urus",
        year: 2024,
        price: 42000,
        hp: 666,
        type: "Кроссовер",
        engine: "4.0L V8 турбо",
        transmission: "Автомат",
        color: "Желтый",
        description: "Самый мощный серийный внедорожник в мире с характером суперкара.",
        images: ["images/lambo_urus_1.jpg", "images/lambo_urus_2.jpg", "images/lambo_urus_3.jpg"]
    },
    {
        id: 59,
        brand: "Lamborghini",
        model: "Revuelto",
        year: 2024,
        price: 75000,
        hp: 1015,
        type: "Купе",
        engine: "6.5L V12 гибрид",
        transmission: "Автомат",
        color: "Оранжевый",
        description: "Новый флагман Lamborghini с гибридным V12 и рекордной мощностью.",
        images: ["images/lambo_revuelto_1.jpg", "images/lambo_revuelto_2.jpg", "images/lambo_revuelto_3.jpg"]
    },
    {
        id: 60,
        brand: "Lamborghini",
        model: "Aventador",
        year: 2024,
        price: 60000,
        hp: 780,
        type: "Купе",
        engine: "6.5L V12",
        transmission: "Автомат",
        color: "Черный",
        description: "Легендарный суперкар с атмосферным V12 и дверями типа «крылья бабочки».",
        images: ["images/lambo_aventador_1.jpg", "images/lambo_aventador_2.jpg", "images/lambo_aventador_3.jpg"]
    }
];